//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MyCvProject.Models.Entity
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class TblContact
    {
        public int ID { get; set; }
        [Required(ErrorMessage = "Cannot be left empty")]
        public string NameSurname { get; set; }
        [Required(ErrorMessage = "Cannot be left empty")]
        public string Mail { get; set; }
        [Required(ErrorMessage = "Cannot be left empty")]
        public string Subject { get; set; }
        [Required(ErrorMessage = "Cannot be left empty")]
        public string Message { get; set; }
        [Required(ErrorMessage = "Cannot be left empty")]

        public Nullable<System.DateTime> Date { get; set; }
    }
}
