//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MyCvProject.Models.Entity
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class TblExperience
    {
        public int ID { get; set; }
        [Required(ErrorMessage ="Cannot be left empty")]
        public string Title { get; set; }
        [Required(ErrorMessage = "Cannot be left empty")]
        public string SubTitle { get; set; }
        [Required(ErrorMessage = "Cannot be left empty")]
        public string Description { get; set; }

        public string Date { get; set; }
    }
}
